version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/repo
      - run:
        name: Installing dependencies
        command: yarn install

  build_launcher_graphql:
    branches:
      only: master
    docker:
      - image: circleci/node:9
    working_directory: ~/repo/packages/launcher-graphql
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
        name: Packaging for Linux (x64)
        command: yarn build:linux-x64
          - run:
            name: Packaging for FreeBSD (x64)
            command: yarn build:freebsd-x64
      - run:
        name: Packaging for Windows (x64)
        command: yarn build:windows-x64
      - run:
        name: Packaging for OSX (x64)
        command: yarn build:macos-x64

workflows:
  version: 2
  build-artifacts:
    jobs:
      - checkout-code
      - build_launcher_graphql:
        requires:
          - checkout_code
        filters:
          branches:
            only: master
